email: "your_email@example.com"
password: "your_password"

events:
  - link: "https://www.meetup.com/some-group/events/123456789/"
    rsvp_time: "18:30-25-04-2025"

  - link: "https://www.meetup.com/another-group/events/987654321/"
    rsvp_time: "20:00-30-04-2025"